name: Run unit tests

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating System'
        required: true
        type: choice
        options:
          - windows-latest
          - ubuntu-latest
          #- macos-latest
      tests:
        required: false
        type:     boolean
        default:  true
  workflow_call:
    #need to repeat the inputs (https://github.com/orgs/community/discussions/39357)
    inputs:
      os:
        description: 'Operating System'
        required: true
        type: string
        #type: choice    #not supported
        #options:
        #  - windows-latest
        #  - ubuntu-latest
        #  - macos-latest
      tests:
        required: false
        type:     boolean
        default:  true


jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          repository: alexander-g/traininglib
          submodules: 'recursive'
      
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14

      - name: Build C++ extension
        run: |
          mkdir cpp/build && cd cpp/build
          cmake ..
          cmake --build . --config Release
          cd ../..
      
      - name: Archive C++ extension
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            cpp/build/**/TSinterface.dll
            cpp/build/*.so
          retention-days: 1
      
  test:
    if:      ${{ inputs.tests }}
    runs-on: ${{ inputs.os }}
    needs:   build
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: '**/requirements.frozen.txt'

      - name: Install requirements
        run: pip install -r requirements.frozen.txt

      - name: Run tests
        run: bash ./run_tests.sh
